run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-dirs:
    - vendor
    - .git
    - deployments
    - docs
    - web
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"

output:
  formats:
    - format: colored-line-number
      print-issued-lines: true
      print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable:
      - shadow
    
  gocyclo:
    min-complexity: 15
    
  maligned:
    suggest-new: true
    
  dupl:
    threshold: 100
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  misspell:
    locale: US
    
  lll:
    line-length: 150
    
  goimports:
    local-prefixes: proxy-platform
    
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport
      
  funlen:
    lines: 80
    statements: 50
    
  gocognit:
    min-complexity: 15
    
  depguard:
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - github.com/XXXXD-cation/proxy-platform
          - github.com/go-redis/redis/v8
          - github.com/redis/go-redis/v9
          - github.com/go-redis/redismock/v8
          - github.com/go-sql-driver/mysql
          - github.com/sirupsen/logrus
          - gopkg.in/yaml.v3
          - gorm.io/gorm
          - gorm.io/driver/mysql
          - gorm.io/datatypes
          - github.com/gin-gonic/gin
          - github.com/golang-jwt/jwt/v5
          - github.com/google/uuid
          - github.com/stretchr/testify/suite
          - github.com/stretchr/testify/assert

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - copyloopvar
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    
  disable:
    - prealloc

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit
        
    # Exclude known linters from partially hard-to-fix issues
    - linters:
        - lll
      source: "^//go:generate "
      
    # Exclude shadow warnings for short variable names
    - linters:
        - govet
      text: "shadow: declaration of \"(err|ctx|tx|ok)\""
      
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0 